/**
*  Author: Cloud Lending Solutions
*  Description: Object Wrapper for verterx request 
*
**/
public class VertexRequestObject {
    Public String id {get;set;}
    Public String name{get;set;}
    public string AppName{get;set;}
    Public String StartDate{get;set;}
    Public String EndDate{get;set;}
    Public String lengthOfContract{get;set;}
    Public String lineItemId{get;set;}
    Public String customer{get;set;}
    Public string city{get;set;}
    Public string state{get;set;}
    Public string mainDivision{get;set;}
    Public string zipCode{get;set;}
    Public string productValue{get;set;}
    Public string ddlAmount{get;set;}
    Public string assetNumber{get;set;}
    Public string duetype{get;set;}
    Public string ApplicaionNumber{get;set;}
    public string sellingPrice {get;set;}
    public string serialnumber{get;set;}
    
    /*Public string CodeFieldId1{get;set;}
    Public string CodeFieldId2{get;set;}
    Public string CodeFieldId3{get;set;}
    Public string CodeFieldId4{get;set;}
    Public string CodeFieldId5{get;set;}
    Public string CodeFieldId6{get;set;}
    Public string CodeFieldId7{get;set;}
    Public string CodeFieldId8{get;set;}
    Public string CodeFieldId9{get;set;}
    Public string CodeFieldId10{get;set;}
    Public string CodeFieldId11{get;set;}
    Public string CodeFieldId12{get;set;}
    Public string CodeFieldId13{get;set;}
    Public string CodeFieldId14{get;set;}
    Public string CodeFieldId15{get;set;}
    Public string CodeFieldId16{get;set;}
    Public string CodeFieldId17{get;set;}
    Public string CodeFieldId18{get;set;}
    Public string NumericFieldId1{get;set;}
    Public string NumericFieldId2{get;set;}
    Public string NumericFieldId3{get;set;}
    Public string NumericFieldId4{get;set;}
    Public string NumericFieldId5{get;set;}*/
    Public string DateFieldId{get;set;}
}