/**
*  Author: Cloud Lending Solutions
*  Description: Object Wrapper for verterx response 
*
**/
public class VertexResponseObject {
    String Company;
    String Division;
    String SubTotal;
    String Total;
    String TotalTax;
    String lineItemId;
    String taxAreaId;
    String City;
    String MainDivision;
    String PostalCode;
    String Product;
    String quantity;
    String fairMarketValue;
    String ExtendedPrice;
    String Taxresult;
    String TaxType;
    String situs;
    String taxcollectedfromparty;
    String taxStructure;
    String jurisdictionLevel;
    String jurisdictionId;
    String CalculatedTax;
    String EffectiveRate;
    String Taxable;
    String impositionId;
    String Imposition;
    String ImpositionType;
	String ImpositionTypeid;
    String TaxRuleId;
    String InclusionRuleId;
    //String TotalTax;
    /*string CodeFieldId1;
    string CodeFieldId2;
    string CodeFieldId3;
    string CodeFieldId4;
    string CodeFieldId5;
    string CodeFieldId6;
    string CodeFieldId7;
    string CodeFieldId8;
    string CodeFieldId9;
    string CodeFieldId10;
    string CodeFieldId11;
    string CodeFieldId12;
    string CodeFieldId13;
    string CodeFieldId14;
    string CodeFieldId15;
    string CodeFieldId16;
    string CodeFieldId17;
    string CodeFieldId18;
    string NumericFieldId1;
    string NumericFieldId2;
    string NumericFieldId3;
    string NumericFieldId4;
    string NumericFieldId5;*/
    string DateFieldId;
    string AssistedParameter;
    string AssistedParameterName;
    String phase;
    String rulename;
    String originalValue;
}